language: java
jdk:
- oraclejdk8
deploy:
- provider: openshift
  user: olivier@nadeva.fr
  password:
    secure: 7V+3DHlEvg1JlwX87C0t9S78WIBn/unsOEg/5ypnen85hNzhVBd5RgdE4nHEWXQEC77QIXT3tFra6WGpBNc9mGYbahGBQh3In7t5aHknDolkys1XCOZsUy2H5qzl6AMZW1eHb2sYqVI2N1Z1G0Tc28oEpR+2I7PsEoOY2UPtmQ+eGhYAABGZKLfaVXE4HKrk39m45Z32668IGts9zLJHRtiC8D+ebjWawo5uIkrFneRJJuUXkXpanE151t0f3GYXxbHsXnFkBk82x7ovkGY4it7z8bO1kGp56kILuR66gveOxtDGCLLNyRBZxYT+UO0xdinMesRZAjSeCunrEgEwA05DaHSDkcgvzXyWCfruWGdLPaAnEdnCf0527baU0uOZFiZIqvuIImzepkd7fmxF2/YNO987PGHyKkwgSEe4WaixJeTTqBxA8ZuFOZ5flrEwf4G1yw/1d73bx/bTzTaJoAZCgDN/j8u5nmisNcjWE58AQfHpCuWUO5Gq3BTy7ZMgREPQmxO5O9rk1Y/J58Eglt7VPCmDP2xOggxpHLB/ci9d1XLpbCbqsG2Wfu8kv8K7wvj/TASoKYd9PdsKD38HZkxsXant30Fv4zPzEZwagxXpVGowelasjczgYd7vizmhzMhmdYCBOIKFqdRlPvlGw4UmfuKUxUHI23JAyH/rl3w=
  app: bookstore
  domain: nadeva
  on:
    repo: nadeva/javaee-bookstore
    branch: master
- provider: heroku
  skip_cleanup: true
  api_key:
    secure: VBk6kxTqYNI35EDyzAuzLAjSkcZ3sqiM4OqBcEIWwILnM5u0Myxq8waYNVKydHJdTUfWnA1CTex1clXDt5Gr/3TTd1Z1k5hFM1QDv0puEpTn0CRYFo1cNmeONO0Zc5fp1z/SDFv23A7kszt9f13mo9/3ML44n95TridFoEQ6KiOZsfs6RKGB9bMNpkEsYB7HZIpm6coKY8Dxc1jYHG8QcH9yioUGY3vPeT8LTh0rBg4KUJjPduf4i1sUbGpu8PiG6HvsrxDf2KbQdPKmF8my08/SqCHy/OdT6Z8Z6lp7zRfV2wUQ+E1hRPYFSQP76fjfP0fmOyXqRyvNscM94w90m959lyVNJCiHo4yEYhhc5q8ID1ijf3h9gQrwphdrGmCiwwTZorhCRW5PixzDyZYE/VcfiYmgGHc1UpJ70VLouME8WgqNi3FkldlE8LT3iY5CI2DhAI6Pm0xc5DOiFbw5xBGaKBft/beFULM2WjOAK+IIXdAgFEyzYVykD+bfxpoNvpE3APboB1Cwrufv2wriOsUbwxwRsDMxbTLahemAMtUtoKKdNn5Q57LCrRGyJ7J/ITXBg5dT+yl1LgOUsI3JwudwuD8DYzb/2HLtbI4WeJB1gxhkkAcZjQVOyFDZFlsx2tE8H/i4EWqDTdQcu4OPAmVhNjJDT0lPpfVYG8uv4w0=
  app: javaee-bookstore
  on:
    repo: nadeva/javaee-bookstore
notifications:
  slack:
    secure: 7Cz9dIpVXauQ8eARIXIcazbNqLJBaXSM48NcTJx6L38Fu1cUyjxcOp1KFwe4mTto0JT+zXtQw1mzCjt7mkr5SX9YzvNGMjoYTXm5Aqv21ACUaVIXyairv0kk2fXmojKmJ2qFf5Q34sIIPCFaSUV079l8KLgBIt0EWca5Z9qL8oluWUg9slUn5O5CAeZHi9OiFpF7dUFpEzPXCBe452annpcaV8azP3vWPJ3fJjpZd6Vq9TyGAtUNT7Ml8BwDBFg2Nq7EfWdGFzPrJ5tclmTHXMIwWxxgm0oH60aQM7eQicnyWA67dTfyJ1RK9OANF8sFQm02gtUBYMrd5prIuvkxsgf+OZpNTsF79I6Qxz9XJAPrh1eRnA/iR08NZuf/rEJV5eJJGA/N8FWvcx6QQdWe3O3DdBe/SOPOa9L8ItKOJubxBLrqkSWi+qXQQwE2z9i0xSAc9v1vJ4MAmTO367aR8WngHJzMjrcTXsCJAeTt7HhwYauAbz4Obgw0KAhfs8logbY0KYGCm0Js0yEKVMAg/WZNG3KFTrQaSaMmHGCdqNc9Vv/wON0Ru0i9X5MZFv6SKG11+rnIMP1uYjEmD1JnMZUeZk9IuU9I2jUWyMrPWCTIyFV6yOJfmOQ4AUA6pEIYSD+zgNmXEKA32ubtWKZ7MpSGn0kCnVmCBgoF8vAL5zw=
    on_success: change
