language: java
cache:
  directories:
  - "$HOME/.m2"
git:
  depth: 3
jdk:
- openjdk11
jobs:
  include:
  - stage: Build
    script: mvn install -B
  - stage: Build and deploy
    script:
    - mvn clean install -Pthorntail -B
    before_deploy: sed -i -e 's:<activeByDefault>false</activeByDefault>:<activeByDefault>true</activeByDefault>:g'
      pom.xml
    deploy:
    - provider: heroku
      skip_cleanup: true
      api_key:
        secure: frzzCuGg6xEjEnKFVFHqRsZS8xIRMHWiVp7pem57gBu2CnDHEq+ibzs+2wCiDFnBXRs7Nz3fbsxhv1yd9GepzNHH4H5GE1AJpWk3wYdjcu5sjFtWTlbMJo4iSYijs4s+yJy77oZW7fVjV8WmzkAXfR2x1Ek2+PaTasvZOM6dCZlHkpqdrvnim4rQUl5xkGhfKpo3mk6Wn/KKCCti/ujVI0pP7w16wCLuag+KDHYpK2f5IFrOu+PiUJzgRkKwHguRK5zPMr64VOe2l7z+EW5hFzFuBFvIjVvr3U2lCF1kggFIRXHtj7KmyQ2vhgUPSlLY+nn5pm7FBD2hlJUtfFl29o2sLFkzI6db7Oof/Ah3hkjvvjJ2QDciF7xSrEzPbTtC7A4K6Azhy86QLmV4xPg63wOk8J2OO4Ike1n0p1R2LMnDbOxDgrYwvGlSrvvfT4/uIdUTTQucw1y2BHEkIxIQ+HOzGnfNzK5R/sNNr5HS4EZbCU0NchHfntfLJv8bkLYCVLNU2x45UFdlnT5B9YOmmHO9p5bvupzQIIlpcjdpGUc7ksGfIosfiArNa9f2ijNLNFa3v5K76t494VOlJJVD+G4zwyCm+HUYMp6WCbK6EKc0MNOMAyRGwDsein1XNHQ3a81ToG7KOkzyzXRSdr68nqIUBqVMTPTwKmyEX0hSktY=
      app: javaee-bookstore
      on:
        repo: nadeva/javaee-bookstore
    notifications:
      slack:
        secure: 7Cz9dIpVXauQ8eARIXIcazbNqLJBaXSM48NcTJx6L38Fu1cUyjxcOp1KFwe4mTto0JT+zXtQw1mzCjt7mkr5SX9YzvNGMjoYTXm5Aqv21ACUaVIXyairv0kk2fXmojKmJ2qFf5Q34sIIPCFaSUV079l8KLgBIt0EWca5Z9qL8oluWUg9slUn5O5CAeZHi9OiFpF7dUFpEzPXCBe452annpcaV8azP3vWPJ3fJjpZd6Vq9TyGAtUNT7Ml8BwDBFg2Nq7EfWdGFzPrJ5tclmTHXMIwWxxgm0oH60aQM7eQicnyWA67dTfyJ1RK9OANF8sFQm02gtUBYMrd5prIuvkxsgf+OZpNTsF79I6Qxz9XJAPrh1eRnA/iR08NZuf/rEJV5eJJGA/N8FWvcx6QQdWe3O3DdBe/SOPOa9L8ItKOJubxBLrqkSWi+qXQQwE2z9i0xSAc9v1vJ4MAmTO367aR8WngHJzMjrcTXsCJAeTt7HhwYauAbz4Obgw0KAhfs8logbY0KYGCm0Js0yEKVMAg/WZNG3KFTrQaSaMmHGCdqNc9Vv/wON0Ru0i9X5MZFv6SKG11+rnIMP1uYjEmD1JnMZUeZk9IuU9I2jUWyMrPWCTIyFV6yOJfmOQ4AUA6pEIYSD+zgNmXEKA32ubtWKZ7MpSGn0kCnVmCBgoF8vAL5zw=
        on_success: change
